//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int PlaceId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Facility { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Suburb { get; set; }
        public int ActivityActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
